# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_Review',
            new_name='ProductReview',
        ),
        migrations.RenameModel(
            old_name='Seller_Review',
            new_name='SellerReview',
        ),
    ]
