# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-19 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0002_auto_20170519_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
