# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0007_auto_20170522_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
