# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 12:34
from __future__ import unicode_literals

import decommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0008_auto_20170522_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=decommerce.models.content_file_name),
        ),
    ]
