# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0010_productreview_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.CharField(max_length=280),
        ),
    ]
