# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-05 09:32
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0012_auto_20170523_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='sellerprofile',
            name='store_name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='stars',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(choices=[('ITA', 'Italia'), ('ENG', 'Ingilterra'), ('USA', 'Stati Uniti'), ('FRA', 'Francia'), ('SPA', 'Spagna')], max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
