# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0015_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
