# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0016_auto_20170607_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decommerce.UserProfile'),
        ),
        migrations.AlterField(
            model_name='sellerreview',
            name='by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='decommerce.UserProfile'),
        ),
    ]
