# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0017_auto_20170607_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerreview',
            name='by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='decommerce.UserProfile'),
        ),
    ]
