# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-08 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0018_auto_20170607_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerreview',
            name='title',
            field=models.CharField(default='Titolo', max_length=30),
            preserve_default=False,
        ),
    ]
