# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 09:33
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0022_auto_20170612_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(choices=[('ITA', 'Italia'), ('ENG', 'Inghilterra'), ('USA', 'Stati Uniti'), ('FRA', 'Francia'), ('SPA', 'Spagna')], max_length=3, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='decommerce.Tags'),
        ),
    ]
