# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0023_auto_20170615_0933'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
