# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0027_auto_20170626_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(),
        ),
    ]
