# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-07 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('decommerce', '0028_auto_20170706_0728'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productreview',
            unique_together=set([('product', 'by')]),
        ),
        migrations.AlterUniqueTogether(
            name='sellerreview',
            unique_together=set([('seller', 'by')]),
        ),
    ]
